crypt:
  encoder: base64
  password: null
environment: development
feed:
  default_tags:
    - rssfeed
google:
  news:
    urls:
      root: https://news.google.com/rss/search?hl=ja&gl=JP&ceid=JP%3Aja
http:
  retry:
    limit: 3
    seconds: 1
lemmy:
  subject:
    max_length: 100
  urls:
    api: /api/v3/ws
  verify_peer: true
line:
  urls:
    api: https://api.line.me
package:
  authors:
    - Tatsuya Koishi
  description: 投稿のソース・投稿先・スケジュールの3要素を組み合わせた、単純なつぶやきボットを作成するツール。複数のボットが管理できる。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/tomato-shrieker
  version: 3.4.8
slack:
  hooks: []
sources: []
sqlite3:
  db: db.sqlite3
tweet:
  urls:
    root: https://nitter.net
websocket:
  keepalive: 15
