package:
  version: 3.2.15
  url: https://github.com/pooza/tomato-shrieker
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ボット作成支援ツール。 新着記事やコマンドの実行結果を、fediverse、Slack互換webhook、LINE、Lemmyに投稿する。
  license: MIT
environment: development
sqlite3:
  db: db.sqlite3
slack:
  hooks: []
http:
  retry:
    limit: 3
    seconds: 1
websocket:
  keepalive: 15
crypt:
  password: null
  encoder: base64
line:
  urls:
    api: https://api.line.me
lemmy:
  urls:
    api: /api/v3/ws
