package:
  version: 3.2.0
  url: https://github.com/pooza/tomato-shrieker
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ボット作成支援ツール。 新着記事やコマンドの実行結果を、fediverseやSlack互換webhookに投稿する。
  license: MIT
environment: development
test:
  filters:
    - name: ci
      cases: []
sqlite3:
  db: db.sqlite3
slack:
  hooks: []
