crypt:
  encoder: base64
  password: null
environment: development
feed:
  default_tags:
    - rssfeed
github:
  urls:
    root: https://github.com
google:
  news:
    urls:
      root: https://news.google.com/rss/search?hl=ja&gl=JP&ceid=JP%3Aja
http:
  retry:
    limit: 3
    seconds: 1
lemmy:
  subject:
    max_length: 100
  urls:
    api: /api/v3/ws
  verify_peer: true
line:
  urls:
    api: https://api.line.me
logger:
  mask_fields:
    - password
    - secret
    - auth
package:
  authors:
    - Tatsuya Koishi
  description: 投稿のソース・投稿先・スケジュールの3要素を組み合わせた、単純なつぶやきボットを作成するツール。複数のボットが管理できる。
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/tomato-shrieker
  version: 3.4.17
slack:
  hooks: []
source:
  classes:
    - class: FeedSource
      config: /source/feed
    - class: FeedSource
      config: /source/url
    - class: CommandSource
      config: /source/command
    - class: TextSource
      config: /source/text
    - class: GoogleNewsSource
      config: /source/news/url
    - class: GoogleNewsSource
      config: /source/news/phrase
    - class: TweetTimelineSource
      config: /source/tweet/account
    - class: GitHubRepositorySource
      config: /source/github/repository
    - class: GitHubRepositorySource
      config: /source/github/repos
sources: []
sqlite3:
  db: db.sqlite3
tweet:
  urls: # @see https://github.com/xnaas/nitter-instances
    - https://nitter.net/
    - https://nitter.lacontrevoie.fr/
    - https://nitter.pussthecat.org/
    - https://nitter.fdn.fr/
    - https://nitter.1d4.us/
    - https://nitter.kavin.rocks/
    - https://birdsite.xanny.family/
    - https://twitter.censors.us/
    - https://twitter.076.ne.jp/
    - https://nitter.fly.dev/
websocket:
  keepalive: 15
