package:
  version: 3.1.5
  url: https://github.com/pooza/tomato-shrieker
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
test:
  filters:
    - name: ci
      cases: []
sqlite3:
  db: db.sqlite3
slack:
  hooks: []
