package:
<<<<<<< HEAD
  version: 3.0.9
=======
  version: 3.1.0
>>>>>>> 3_1_0
  url: https://github.com/pooza/tomato-toot
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
sqlite3:
  db: db.sqlite3
slack:
  hooks: []
