package:
  version: 3.2.8
  url: https://github.com/pooza/tomato-shrieker
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ボット作成支援ツール。 新着記事やコマンドの実行結果を、fediverse、Slack互換webhook、LINEに投稿する。
  license: MIT
environment: development
sqlite3:
  db: db.sqlite3
slack:
  hooks: []
http:
  retry:
    limit: 3
    seconds: 1
