package:
  version: 2.3.2
  url: https://github.com/pooza/tomato-toot
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
cert:
  url: https://curl.haxx.se/ca/cacert.pem
slack:
  hooks: []
entries: []
