filters:
  - cases: []
    name: ci
  - cases:
      - google_news_source
      - news_entry
    name: google_news
  - cases:
      - line_shrieker
    name: line
  - cases:
      - lemmy_shrieker
    name: lemmy
  - cases:
      - entry
    name: entry
