filters:
  - cases:
      - webhook_shrieker
    name: webhook
  - cases:
      - mastodon_shrieker
    name: mastodon
  - cases:
      - misskey_shrieker
    name: misskey
  - cases:
      - line_shrieker
    name: line
  - cases:
      - lemmy_shrieker
    name: lemmy
  - cases:
      - entry
    name: entry
