name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-buildx-action@v2
    - run: |
        IMAGE_ID=${{ github.repository }}
        IMAGE_ID=${IMAGE_ID,,}
        echo "image_tag=$IMAGE_ID" >> $GITHUB_ENV

    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ env.image_tag }}:${{ github.sha }},ghcr.io/${{ github.image_tag }}:dev
