name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-buildx-action@v2

    - uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/tomato-shrieker:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/tomato-shrieker:dev
