name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
          - 2.6.x
          - 2.7.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - run: bundle exec rubocop
      - run: bundle exec rake test
