name: test
on:
  - push
env:
  CI: "true"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: apt install
        run: |
          sudo apt update
          sudo apt install libsqlite3-dev
      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3
          bundle exec rake bundle:update
          bundle exec rake bundle:check
      - run: bundle exec migrate
      - run: bundle exec rubocop
      - run: #bundle exec rake test
